# Generated by Django 2.1.7 on 2019-03-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190316_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=16)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
