# Generated by Django 2.1.7 on 2019-03-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190316_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], max_length=20)),
                ('scholarship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarshipapplication', to='api.Scholarship')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentapplication', to='api.Student')),
            ],
        ),
    ]
