# Generated by Django 2.1.7 on 2019-03-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='api.Organisation'),
        ),
    ]
