# Generated by Django 2.1.7 on 2019-03-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190316_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='max_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='min_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='uid',
        ),
    ]
