# Generated by Django 2.1.7 on 2019-03-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190316_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='username',
        ),
    ]
