# Generated by Django 2.1.7 on 2019-03-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_scholarship_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='form_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='course',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('Class 11', 'Class 11'), ('Class 12', 'Class 12'), ('Diploma', 'Diploma'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('PhD', 'PhD'), ('Post Doctoral', 'Post Doctoral'), ('ITI', 'ITI'), ('Others', 'Others')], default='', max_length=50),
        ),
    ]
