# Generated by Django 2.1.7 on 2019-09-20 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_auto_20190921_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 21, 0, 35, 50, 193400)),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 21, 0, 35, 50, 192400)),
        ),
    ]
