# Generated by Django 2.1.7 on 2019-09-21 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0009_auto_20190921_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 21, 6, 37, 54, 733807)),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 21, 6, 37, 54, 733807)),
        ),
    ]
